version: '2'

services:
  db:
    image: postgres:11
    environment:
      POSTGRES_DB: feeds_app
      POSTGRES_USER: feeds
      POSTGRES_PASSWORD: feeds_pass
    ports:
      - 5432:5432

  redis_cache:
    image: redis
    ports:
      - 6379:6379
